pdf: coxme.pdf  variance.pdf lmekin.pdf laplace.pdf

coxme.pdf: coxme.tex
	texi2dvi --pdf coxme.tex

variance.pdf: variance.tex
	texi2dvi variance.tex

lmekin.pdf: lmekin.tex
	texi2dvi lmekin.tex

laplace.pdf: laplace.tex
	texi2dvi laplace.tex

clean:
	rm *.tex cfig*.pdf *.aux *.log
